version: "3.9"

services:
  web:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "127.0.0.1:8000:80"
    restart: unless-stopped

  api:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "127.0.0.1:4000:4000"
    restart: unless-stopped
